01_AUS:
  STOCKS_PER_CAPITA_PCT_DIFF_THRESHOLD: 0.1
  USE_SAME_MILEAGE_ACROSS_VEHICLE_TYPES: true
  iteration_multiplier: 10
  maximum_proportional_change_in_intensity: 0.2
  maximum_proportional_change_in_mileage: 0.2
  maximum_proportional_change_in_stocks: 5
  method: L-BFGS-B
  mse_stocks_dominant_vehicles_exponent: 0.3
  tolerance_pct: 0.0001
  w_mse_energy: 1
  w_mse_intensity: 0.5
  w_mse_mileage: 0.5
  w_mse_opposite_drive_types: 1
  w_mse_spc: 0
  w_mse_stocks: 1
02_BD:
  STOCKS_PER_CAPITA_PCT_DIFF_THRESHOLD: 0.3
  USE_SAME_MILEAGE_ACROSS_VEHICLE_TYPES: true
  iteration_multiplier: 10
  maximum_proportional_change_in_intensity: 0.2
  maximum_proportional_change_in_mileage: 0.2
  maximum_proportional_change_in_stocks: 5
  method: L-BFGS-B
  mse_stocks_dominant_vehicles_exponent: 0.3
  tolerance_pct: 0.0001
  w_mse_energy: 1
  w_mse_intensity: 0.5
  w_mse_mileage: 0.5
  w_mse_opposite_drive_types: 1
  w_mse_spc: 0.1
  w_mse_stocks: 1
03_CDA:
  STOCKS_PER_CAPITA_PCT_DIFF_THRESHOLD: 0.5
  USE_SAME_MILEAGE_ACROSS_VEHICLE_TYPES: true
  iteration_multiplier: 10
  maximum_proportional_change_in_intensity: 0.2
  maximum_proportional_change_in_mileage: 0.2
  maximum_proportional_change_in_stocks: 5
  method: L-BFGS-B
  mse_stocks_dominant_vehicles_exponent: 0.3
  tolerance_pct: 0.0001
  w_mse_energy: 1
  w_mse_intensity: 0.5
  w_mse_mileage: 0.5
  w_mse_opposite_drive_types: 1
  w_mse_spc: 0.1
  w_mse_stocks: 1
04_CHL:
  STOCKS_PER_CAPITA_PCT_DIFF_THRESHOLD: 0.1
  USE_SAME_MILEAGE_ACROSS_VEHICLE_TYPES: true
  iteration_multiplier: 10
  maximum_proportional_change_in_intensity: 0.2
  maximum_proportional_change_in_mileage: 0.2
  maximum_proportional_change_in_stocks: 10
  method: L-BFGS-B
  mse_stocks_dominant_vehicles_exponent: 0.3
  tolerance_pct: 0.0001
  w_mse_energy: 1
  w_mse_intensity: 0.5
  w_mse_mileage: 0.5
  w_mse_opposite_drive_types: 1
  w_mse_spc: 0.1
  w_mse_stocks: 1
05_PRC:
  STOCKS_PER_CAPITA_PCT_DIFF_THRESHOLD: 0.1
  USE_SAME_MILEAGE_ACROSS_VEHICLE_TYPES: true
  iteration_multiplier: 10
  maximum_proportional_change_in_intensity: 0.2
  maximum_proportional_change_in_mileage: 0.2
  maximum_proportional_change_in_stocks: 5
  method: L-BFGS-B
  mse_stocks_dominant_vehicles_exponent: 0.3
  tolerance_pct: 0.0001
  w_mse_energy: 1
  w_mse_intensity: 0.5
  w_mse_mileage: 0.5
  w_mse_opposite_drive_types: 1
  w_mse_spc: 0.1
  w_mse_stocks: 0.01
06_HKC:
  STOCKS_PER_CAPITA_PCT_DIFF_THRESHOLD: 0.1
  USE_SAME_MILEAGE_ACROSS_VEHICLE_TYPES: true
  iteration_multiplier: 10
  maximum_proportional_change_in_intensity: 0.2
  maximum_proportional_change_in_mileage: 0.2
  maximum_proportional_change_in_stocks: 5
  method: L-BFGS-B
  mse_stocks_dominant_vehicles_exponent: 0.3
  tolerance_pct: 0.0001
  w_mse_energy: 1
  w_mse_intensity: 0.5
  w_mse_mileage: 0.5
  w_mse_opposite_drive_types: 1
  w_mse_spc: 0
  w_mse_stocks: 0.5
07_INA:
  STOCKS_PER_CAPITA_PCT_DIFF_THRESHOLD: 0.1
  USE_SAME_MILEAGE_ACROSS_VEHICLE_TYPES: true
  iteration_multiplier: 10
  maximum_proportional_change_in_intensity: 0.2
  maximum_proportional_change_in_mileage: 0.2
  maximum_proportional_change_in_stocks: 5
  method: L-BFGS-B
  mse_stocks_dominant_vehicles_exponent: 0.3
  tolerance_pct: 0.0001
  w_mse_energy: 1
  w_mse_intensity: 0.5
  w_mse_mileage: 0.5
  w_mse_opposite_drive_types: 1
  w_mse_spc: 0.1
  w_mse_stocks: 1
08_JPN:
  STOCKS_PER_CAPITA_PCT_DIFF_THRESHOLD: 0.1
  USE_SAME_MILEAGE_ACROSS_VEHICLE_TYPES: true
  iteration_multiplier: 10
  maximum_proportional_change_in_intensity: 0.2
  maximum_proportional_change_in_mileage: 0.2
  maximum_proportional_change_in_stocks: 5
  method: L-BFGS-B
  mse_stocks_dominant_vehicles_exponent: 0.3
  tolerance_pct: 0.0001
  w_mse_energy: 1
  w_mse_intensity: 0.5
  w_mse_mileage: 0.5
  w_mse_opposite_drive_types: 1
  w_mse_spc: 0
  w_mse_stocks: 1
09_ROK:
  STOCKS_PER_CAPITA_PCT_DIFF_THRESHOLD: 0.5
  USE_SAME_MILEAGE_ACROSS_VEHICLE_TYPES: true
  iteration_multiplier: 10
  maximum_proportional_change_in_intensity: 0.2
  maximum_proportional_change_in_mileage: 0.2
  maximum_proportional_change_in_stocks: 5
  method: L-BFGS-B
  mse_stocks_dominant_vehicles_exponent: 0.3
  tolerance_pct: 0.0001
  w_mse_energy: 1
  w_mse_intensity: 0.5
  w_mse_mileage: 0.5
  w_mse_opposite_drive_types: 1
  w_mse_spc: 0.5
  w_mse_stocks: 1
10_MAS:
  STOCKS_PER_CAPITA_PCT_DIFF_THRESHOLD: 0.1
  USE_SAME_MILEAGE_ACROSS_VEHICLE_TYPES: true
  iteration_multiplier: 10
  maximum_proportional_change_in_intensity: 0.2
  maximum_proportional_change_in_mileage: 0.2
  maximum_proportional_change_in_stocks: 5
  method: L-BFGS-B
  mse_stocks_dominant_vehicles_exponent: 0.3
  tolerance_pct: 0.0001
  w_mse_energy: 1
  w_mse_intensity: 0.5
  w_mse_mileage: 0.5
  w_mse_opposite_drive_types: 1
  w_mse_spc: 0
  w_mse_stocks: 0.5
11_MEX:
  STOCKS_PER_CAPITA_PCT_DIFF_THRESHOLD: 0.1
  USE_SAME_MILEAGE_ACROSS_VEHICLE_TYPES: true
  iteration_multiplier: 10
  maximum_proportional_change_in_intensity: 0.2
  maximum_proportional_change_in_mileage: 0.2
  maximum_proportional_change_in_stocks: 5
  method: L-BFGS-B
  mse_stocks_dominant_vehicles_exponent: 0.3
  tolerance_pct: 0.0001
  w_mse_energy: 1
  w_mse_intensity: 0.5
  w_mse_mileage: 0.5
  w_mse_opposite_drive_types: 1
  w_mse_spc: 0
  w_mse_stocks: 0.5
12_NZ:
  STOCKS_PER_CAPITA_PCT_DIFF_THRESHOLD: 0.1
  USE_SAME_MILEAGE_ACROSS_VEHICLE_TYPES: true
  iteration_multiplier: 10
  maximum_proportional_change_in_intensity: 0.2
  maximum_proportional_change_in_mileage: 0.2
  maximum_proportional_change_in_stocks: 5
  method: L-BFGS-B
  mse_stocks_dominant_vehicles_exponent: 0.3
  tolerance_pct: 0.0001
  w_mse_energy: 1
  w_mse_intensity: 0.5
  w_mse_mileage: 0.5
  w_mse_opposite_drive_types: 1
  w_mse_spc: 0
  w_mse_stocks: 1
13_PNG:
  STOCKS_PER_CAPITA_PCT_DIFF_THRESHOLD: 0.8
  USE_SAME_MILEAGE_ACROSS_VEHICLE_TYPES: true
  iteration_multiplier: 10
  maximum_proportional_change_in_intensity: 0.2
  maximum_proportional_change_in_mileage: 0.2
  maximum_proportional_change_in_stocks: 5
  method: L-BFGS-B
  mse_stocks_dominant_vehicles_exponent: 0.3
  tolerance_pct: 0.0001
  w_mse_energy: 1
  w_mse_intensity: 0.5
  w_mse_mileage: 0.5
  w_mse_opposite_drive_types: 1
  w_mse_spc: 0.1
  w_mse_stocks: 0.01
14_PE:
  STOCKS_PER_CAPITA_PCT_DIFF_THRESHOLD: 0.1
  USE_SAME_MILEAGE_ACROSS_VEHICLE_TYPES: true
  iteration_multiplier: 10
  maximum_proportional_change_in_intensity: 0.2
  maximum_proportional_change_in_mileage: 0.2
  maximum_proportional_change_in_stocks: 5
  method: L-BFGS-B
  mse_stocks_dominant_vehicles_exponent: 0.3
  tolerance_pct: 0.0001
  w_mse_energy: 1
  w_mse_intensity: 0.5
  w_mse_mileage: 0.5
  w_mse_opposite_drive_types: 1
  w_mse_spc: 0
  w_mse_stocks: 0.001
15_PHL:
  STOCKS_PER_CAPITA_PCT_DIFF_THRESHOLD: 0.1
  USE_SAME_MILEAGE_ACROSS_VEHICLE_TYPES: true
  iteration_multiplier: 10
  maximum_proportional_change_in_intensity: 0.2
  maximum_proportional_change_in_mileage: 0.2
  maximum_proportional_change_in_stocks: 5
  method: L-BFGS-B
  mse_stocks_dominant_vehicles_exponent: 0.3
  tolerance_pct: 0.0001
  w_mse_energy: 1
  w_mse_intensity: 0.5
  w_mse_mileage: 0.5
  w_mse_opposite_drive_types: 1
  w_mse_spc: 0
  w_mse_stocks: 0.5
16_RUS:
  STOCKS_PER_CAPITA_PCT_DIFF_THRESHOLD: 0.1
  USE_SAME_MILEAGE_ACROSS_VEHICLE_TYPES: true
  iteration_multiplier: 10
  maximum_proportional_change_in_intensity: 0.2
  maximum_proportional_change_in_mileage: 0.2
  maximum_proportional_change_in_stocks: 5
  method: L-BFGS-B
  mse_stocks_dominant_vehicles_exponent: 0.3
  tolerance_pct: 0.0001
  w_mse_energy: 1
  w_mse_intensity: 0.5
  w_mse_mileage: 0.5
  w_mse_opposite_drive_types: 1
  w_mse_spc: 0
  w_mse_stocks: 1
17_SGP:
  STOCKS_PER_CAPITA_PCT_DIFF_THRESHOLD: 0.1
  USE_SAME_MILEAGE_ACROSS_VEHICLE_TYPES: true
  iteration_multiplier: 10
  maximum_proportional_change_in_intensity: 0.2
  maximum_proportional_change_in_mileage: 0.2
  maximum_proportional_change_in_stocks: 5
  method: L-BFGS-B
  mse_stocks_dominant_vehicles_exponent: 0.3
  tolerance_pct: 0.0001
  w_mse_energy: 1
  w_mse_intensity: 0.5
  w_mse_mileage: 0.5
  w_mse_opposite_drive_types: 1
  w_mse_spc: 0
  w_mse_stocks: 1
18_CT:
  STOCKS_PER_CAPITA_PCT_DIFF_THRESHOLD: 0.1
  USE_SAME_MILEAGE_ACROSS_VEHICLE_TYPES: true
  iteration_multiplier: 10
  maximum_proportional_change_in_intensity: 0.2
  maximum_proportional_change_in_mileage: 0.2
  maximum_proportional_change_in_stocks: 5
  method: L-BFGS-B
  mse_stocks_dominant_vehicles_exponent: 0.3
  tolerance_pct: 0.0001
  w_mse_energy: 1
  w_mse_intensity: 0.5
  w_mse_mileage: 0.5
  w_mse_opposite_drive_types: 1
  w_mse_spc: 0
  w_mse_stocks: 0.5
19_THA:
  STOCKS_PER_CAPITA_PCT_DIFF_THRESHOLD: 0.1
  USE_SAME_MILEAGE_ACROSS_VEHICLE_TYPES: true
  iteration_multiplier: 10
  maximum_proportional_change_in_intensity: 0.2
  maximum_proportional_change_in_mileage: 0.2
  maximum_proportional_change_in_stocks: 5
  method: L-BFGS-B
  mse_stocks_dominant_vehicles_exponent: 0.3
  tolerance_pct: 0.0001
  w_mse_energy: 1
  w_mse_intensity: 0.5
  w_mse_mileage: 0.5
  w_mse_opposite_drive_types: 1
  w_mse_spc: 0
  w_mse_stocks: 0.01
20_USA:
  STOCKS_PER_CAPITA_PCT_DIFF_THRESHOLD: 0.1
  USE_SAME_MILEAGE_ACROSS_VEHICLE_TYPES: true
  iteration_multiplier: 10
  maximum_proportional_change_in_intensity: 0.2
  maximum_proportional_change_in_mileage: 0.2
  maximum_proportional_change_in_stocks: 5
  method: L-BFGS-B
  mse_stocks_dominant_vehicles_exponent: 0.3
  tolerance_pct: 0.0001
  w_mse_energy: 1
  w_mse_intensity: 0.5
  w_mse_mileage: 0.5
  w_mse_opposite_drive_types: 1
  w_mse_spc: 0
  w_mse_stocks: 1
21_VN:
  STOCKS_PER_CAPITA_PCT_DIFF_THRESHOLD: 0.1
  USE_SAME_MILEAGE_ACROSS_VEHICLE_TYPES: true
  iteration_multiplier: 10
  maximum_proportional_change_in_intensity: 0.2
  maximum_proportional_change_in_mileage: 0.2
  maximum_proportional_change_in_stocks: 5
  method: L-BFGS-B
  mse_stocks_dominant_vehicles_exponent: 0.3
  tolerance_pct: 0.0001
  w_mse_energy: 1
  w_mse_intensity: 0.5
  w_mse_mileage: 0.5
  w_mse_opposite_drive_types: 1
  w_mse_spc: 0
  w_mse_stocks: 1
ALL:
  STOCKS_PER_CAPITA_PCT_DIFF_THRESHOLD:
  - 0.1
  - 0.2
  - 0.3
  - 0.5
  USE_SAME_MILEAGE_ACROSS_VEHICLE_TYPES:
  - true
  - false
  iteration_multiplier:
  - 10
  - 20
  - 30
  - 100
  maximum_proportional_change_in_intensity:
  - 0.2
  maximum_proportional_change_in_mileage:
  - 0.2
  maximum_proportional_change_in_stocks:
  - 5
  methods_list:
  - L-BFGS-B
  mse_stocks_dominant_vehicles_exponent:
  - 0.3
  tolerance_pct:
  - 0.0001
  - 0.001
  - 0.1
  w_mse_energy:
  - 1
  w_mse_intensity:
  - 0.5
  w_mse_mileage:
  - 0.5
  w_mse_opposite_drive_types:
  - 1
  w_mse_spc:
  - 0.1
  - 0.5
  - 1
  - 0
  w_mse_stocks:
  - 1
  - 0.5
  - 0.01
  - 0.001
ALL2:
  STOCKS_PER_CAPITA_PCT_DIFF_THRESHOLD:
  - 0.1
  - 0.2
  - 0.3
  - 0.5
  - 1
  USE_SAME_MILEAGE_ACROSS_VEHICLE_TYPES:
  - true
  - false
  iteration_multiplier:
  - 10
  - 20
  - 30
  - 100
  - 1000
  maximum_proportional_change_in_intensity:
  - 0.2
  - 0.3
  - 0.4
  - 0.5
  maximum_proportional_change_in_mileage:
  - 0.2
  - 0.3
  - 0.4
  - 0.5
  maximum_proportional_change_in_stocks:
  - 5
  - 10
  - 50
  methods_list:
  - L-BFGS-B
  mse_stocks_dominant_vehicles_exponent:
  - 0.3
  tolerance_pct:
  - 0.0001
  - 0.001
  - 0.1
  w_mse_energy:
  - 1
  w_mse_intensity:
  - 0.5
  w_mse_mileage:
  - 0.5
  w_mse_opposite_drive_types:
  - 1
  w_mse_spc:
  - 0.1
  - 0.5
  - 1
  - 0
  w_mse_stocks:
  - 1
  - 0.5
  - 0.01
  - 0.001
